### ISSUE TITLE
[MP] Opening the INFINITY chest in Multiplayer crashes server.

### ISSUE THREAD

**Issue by steelshot** [WanionCane/Avaritiaddons#1]
Reading from the crash report, i'm sure the chest is asking for client stuff.

https://paste.ee/r/z48Zq

EDIT1: Fixed crash report link for future references

**Comment by steelshot** [comment]
Also no longer lets me log in, as soon as the chest comes to sight, i get kicked with an error

**Comment by WanionCane** [comment]
sorry about this, i can't see the log, it seems to be some encoded stuff.
i will try to fix this as soon as possible.

**Comment by WanionCane** [comment]
Could you try with this, please?
[Avaritiaddons-1.0c](https://minecraft.curseforge.com/projects/avaritiaddons/files/2323664)

**Comment by steelshot** [comment]
That seems to fix the Issue, updated OP link for future references
