### ISSUE TITLE
error

### ISSUE THREAD

**Issue by runescapejon** [WanionCane/Avaritiaddons#10]
hello one of my player put ME cells that were full in the infinity chest and he place it on this base and well this happen
https://gyazo.com/725e349b0fdc9b7b127170cd93e45bd1
the only way to fix this i too remove the infinitychest with mcedit or get rid of this addon mod
can you fix this ?

**Comment by WanionCane** [comment]
by putting heavy NBT stuff inside the Infinity Chest, that exceeded the maximum size allowed for NBT data, there is nothing I can do.
but I wonder how many cells he put on it lol

**Comment by runescapejon** [comment]
but can you make a blacklist for some items that use NBT like backpacks mods and ME cells so they cannot be enter in the infinity chest?

**Comment by WanionCane** [comment]
I could, but believe in me, the infinity chest is already super heavy, adding a blacklist would make it even worse.
also, the NBT limit is really big, that's why I wonder how many cells he put on it XD

**Comment by runescapejon** [comment]
i don't even know how many o.o

**Comment by WanionCane** [comment]
probably a lot XD

**Comment by runescapejon** [comment]
alright so there no fix to this right ?
damn

**Comment by WanionCane** [comment]
unfortunately no =/
before releasing it, I tried to fill it as much as possible to see if something similar to this would happen, and it didn't, I will try again soon =P
sorry that I am unable to fix your issue, but at least I will do some research to see what can cause this.
thanks =P
