### ISSUE TITLE
Porting Avaritaddons to 1.10.2/1.11.2?

### ISSUE THREAD

**Issue by JackyyTV** [WanionCane/Avaritiaddons#11]
I know Avaritia has been completely ported to [1.10.2 and 1.11.2](https://mods.curse.com/mc-mods/minecraft/261348-avaritia-1-10). But this mod is still for 1.7.10. I am just wondering if this mod will ever be ported to 1.10.2 / 1.11.2?

**Comment by WanionCane** [comment]
sorry, for now, I am not planning to port it.

**Comment by JackyyTV** [comment]
Alright, hopefully it'll be ported at some point then.

**Comment by onyxromero** [comment]
I wonder if there would be someone interested in porting this over to 1.12...I have such a hard time trying to make mods, I've never done it but if I could mod I'd port it to 1.12.2 and give full credit to WanionCane for his source code.

**Comment by WanionCane** [comment]
sorry for the delay guys, I am working on it.

**Comment by WanionCane** [comment]
[did it](https://www.curseforge.com/minecraft/mc-mods/avaritiaddons/files/2800937), for now without the chests.
hope there is no problem that it is for 1.12.2 =P

**Comment by WanionCane** [comment]
so, this "port" was based on [Bigger Crafting Tables](https://minecraft.curseforge.com/projects/bigger-crafting-tables), my other mod.
