### ISSUE TITLE
[Item Dupe] Dire Auto Crafting & Stack Upgrade (Extra Utils)

### ISSUE THREAD

**Issue by spannerman79** [WanionCane/Avaritiaddons#12]
MC: 1.7.10

You can see it on Youtube via https://youtu.be/PZbnFFE3qxE?t=6m13s

If an item retrieval node has a stack upgrade on it pulling from the Dire Auto Crafting table the first item crafted is duplicated.

I was able to do the same myself as what was shown with the bare mods needed (Extra Utils, Avartia & Avartia Addons

**Comment by WanionCane** [comment]
sorry for the delay.

OMG!! I made this so long ago, but I remember that I haven't tried with the Stack Upgrade.
thanks for letting me know :)

**Comment by spannerman79** [comment]
> thanks for letting me know

No problems.
I love your mods

I know 1.7.10 is passed over by most mod devs due to 1.7.10 being considered EOL, although it would be "nice" to have this bug fixed up *nudge nudge*

**Comment by WanionCane** [comment]
I hope this [Avaritiaddons-1.4.jar](https://minecraft.curseforge.com/projects/avaritiaddons/files/2460516) will fix this issue.

**Comment by steelshot** [comment]
I think this has been fixed, i can only pull 1 item at a time with the retrieval node upgraded with the stack upgrade

Works with both stackable and unstackble items(ie. swords and ingots)

**Comment by WanionCane** [comment]
yay =P

**Comment by spannerman79** [comment]
> I hope this Avaritiaddons-1.4.jar will fix this issue.

It does @WanionCane. I also unable to dupe while using ExtraUtils with stack upgrades.

Thank you once again for taking the time to consider and releasing a fix - even though most mod devs have moved on or consider 1.7.10 EOL.
