### ISSUE TITLE
Item dupe.

### ISSUE THREAD

**Issue by theshadowake** [WanionCane/Avaritiaddons#13]
You can still take things out of the inventory of the compressed chest, from the Avaritiaddons mod, after it's been broken without affecting the chest itself, duplicating the item.

**Comment by WanionCane** [comment]
omg!!
this happens when you interact with the chest with which mod? Applied Energistics?
or this is happening with everything that interacts with the chest?

**Comment by WanionCane** [comment]
I hope this [Avaritiaddons-1.4.jar](https://minecraft.curseforge.com/projects/avaritiaddons/files/2460516) will fix this issue.

**Comment by steelshot** [comment]
Sadly this has not fixed the dupe issue, I'll explain.

1. Place a compressed chest anywhere, put in items in it (cobble, planks etc. works with anything).
2. Set up a block breaker(any, i used OpenBlocks one) with a timer. (Presumably Could be done with just a player, i had none to test with)
3. Open the chest, and wait for the chest to be broken, pull any items out of it as the GUI is still open
4. Pick up the broken chest place it again and open it
5. All of the original contents still remain in the chest

I think theres just missing checking code **when(chest broken) closeGUI;**

**Comment by WanionCane** [comment]
I wasn't expecting this kind of item dupe lol

**Comment by theshadowake** [comment]
Yep basically if you open the chest and have another player break it the gui stays open. You can remove all the items put the chest back down and the items are still in it :)

**Comment by JoeSGT** [comment]
@WanionCane  i am having this issue as well
what @theshadowake  mention

**Comment by JoeSGT** [comment]
you can also
place down  compressed chest then open it while another player break your compressed chest the gui will stay up while you can take items out of the chest
there you can dupe easy

**Comment by steelshot** [comment]
Fixed in #14

**Comment by JoeSGT** [comment]
Thanks you so much <3
