### ISSUE TITLE
Crash appears when it starts.

### ISSUE THREAD

**Issue by YTWhite-kr** [WanionCane/Avaritiaddons#16]
I used google translate.
I am using Avaritia-1.12.2-3.3.0.33-universal, Avaritiaddons-1.12.2-1.1, CodeChickenLib-1.12.2-3.2.3.358-universal and WanionLib-1.12.2-2.4.

But when Minecraft starts, Crash pops up and the game ends.

Even after changing the mod files of Avaritia and WanionLib, Crash keeps popping up, is there any workaround?

[crash-2020-03-22_12.06.35-client.txt](https://github.com/WanionCane/Avaritiaddons/files/4364606/crash-2020-03-22_12.06.35-client.txt)

My java version is 8.

**Comment by WanionCane** [comment]
I tried it here, I made sure that I was using the same version of everything, and it worked fine here, it even worked after changing the config file, so idk what is happening.
