### ISSUE TITLE
Issue with inifity compressor

### ISSUE THREAD

**Issue by amatsukami1** [WanionCane/Avaritiaddons#19]
I have a problem, i want to automation craft all of singularity, but the infinity compressor work isn't same as the basic compressor. I mean, when i am ordering, for example iron singularity, inf compressor save the recipe, and then i cannot order any of singularity, because of compressor store the iron sing recept. Can you please add  mode, that can switch work of inf compressor to basic compressor mode, that is not store 1 
recipe. Acctually, it's illogical, that simple compressor can craft all sing, if u import exact amount of resources, but impowered version of compressor can craft only one sing, if i will not use shift+right click after each sing craft.
vesion 1.12.2

**Comment by amatsukami1** [comment]
or where code line about recipe saving

**Comment by WanionCane** [comment]
Hello, I have an idea, once it is finished, I will let you know, thank you =D
