### ISSUE TITLE
[Suggestion] Compact text for no of stored items in the Infinity Chest, specially for large numbers.

### ISSUE THREAD

**Issue by steelshot** [WanionCane/Avaritiaddons#3]
As it is right now, the no of items, is displayed on every item, once the numbers get big enough they overlap and reading the output is hard.

<a href="http://imgur.com/fC6NQMi"><img src="http://i.imgur.com/fC6NQMi.png" title="Uploaded by MyImgur.eden.fm" alt="" /></a>

What i would suggest having the chest still display item numbers, until more than 64 is present. Once there is more, just show that there is "64+".

Now if the player needs the item count, there could be a possibility to select that slot and show the information about that slot in the chest GUI. ie. example made with paint

<a href="http://imgur.com/ISXoJ6a"><img src="http://i.imgur.com/ISXoJ6a.png" title="Uploaded by MyImgur.eden.fm" alt="" /></a>

**Comment by WanionCane** [comment]
I am planning to do this similarly the way AE does, seems to be nice, don't you think? :P

**Comment by steelshot** [comment]
That is also a possibility, which ever one is easier to code and/or is more lightweight should be the one, i'm just trowing in some bones :)

**Comment by WanionCane** [comment]
unfortunately until now I not find a way to change the "vanilla way" to render itemstacks, I will keep you updated, ok? :)
also, you want to be tester of it? you helped me a lot.
if yes, could you please tell me your nick name in Curse Forge?

**Comment by steelshot** [comment]
Sure, i dont mind, its the same as in here: SteelShot

**Comment by WanionCane** [comment]
been implemented since version [1.0d](https://minecraft.curseforge.com/projects/avaritiaddons/files/2323940)
