### ISSUE TITLE
Crash When Starting

### ISSUE THREAD

**Issue by Dayyer1** [WanionCane/Avaritiaddons#5]
https://www.dropbox.com/s/dko97adlnq0donh/crash-2016-09-06_19.06.57-client.txt?dl=0

It could because I have ~208 mods... but what's one more??

I just know that when I add this mod, my game won't start; it crashes during loading.

(I don't know what this mod adds, but if I were to make any suggestions, I'd say an in-game documentation, and more Thaumcraft. I like Thaumcraft. Thaumcraft is popular. Sorry, I know this is not what's supposed to be in a crash report.)

**Comment by WanionCane** [comment]
this issue may be related to not enough memory to java load classes, you may try to increase the "PermGen" size.
**-XX:MaxPermSize=160m**

or, your .jar is corrupted.

thanks.

**Comment by WanionCane** [comment]
about your comment, some Ingame doc would be nice, but this mod is mainly a learning experience for something way bigger.
about Thaumcraft, yeah, I may add in the future some interaction between Avaritiaddons and Thaumcraft, but no promises XD

**Comment by Dayyer1** [comment]
Ok, thanks for the help. I'm looking into coding my own Thaumcraft addon, so... no rush. :)

**Comment by WanionCane** [comment]
hey, another thing that could be, is your java updated?
it requires Java 8.

**Comment by Dayyer1** [comment]
I'm not sure. I'm running Java 8 on my computer, or something... (worth noting that I took a break from coding, for school) but when I launch Minecraft (using ATLauncher) it says I should be using Java 8, but I'm not sure how to fix it.

**Comment by WanionCane** [comment]
did you find what was causing the problem?

**Comment by Dayyer1** [comment]
No, but I'm guessing I'm using the wrong Java version. I'm using 1.7 something, and I would switch to 1.8, but I'm not sure how to do it through ATLauncher.

**Comment by WanionCane** [comment]
it requires Java 8 to run, so, since we both know what is the issue, I am closing this.
