### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by Leftorius** [WanionCane/Avaritiaddons#7]
I've got this crash everytime, every version you have on curse:
http://pastebin.com/DR7WjBtw

Modpack is FTB Infinity Evolved 2.6 but there are no others errors than your crash. :I

**Comment by Leftorius** [comment]
fixed it.... didn't know that ftb has disabled everything but crafting and that this option would crash your mod :D^^

**Comment by WanionCane** [comment]
sorry about this, I will add a better check in the next version (the Infinity Chest will have no recipe, unfortunately).
