### ISSUE TITLE
Dire Autocrafting Table Crafting Infinity Catalyst

### ISSUE THREAD

**Issue by MK1Ultra** [WanionCane/Avaritiaddons#9]
For crafting the Infinity Catalyst with the Autocrafting Table the Extremely Primordial Pearl ist consumed. 

edit: Also the crafting of Ultimate Stew just gives you just 1 instead of 9 like the Avaritia recipe

I am using FTB Infinity 2.6.0 and Avaritiaddons 1.2d

**Comment by WanionCane** [comment]
sorry for the delay =/
weird, I tried here, the Extremely Primordial Pearl is being consumed.
about it's outputing just one instead of 9, thanks for saying, probably a lot of people saw it and didn't said anything lol
it will be fixed on the next release :)

**Comment by MK1Ultra** [comment]
Thanks

**Comment by WanionCane** [comment]
it is working now? I mean, the Extremely Primordial Pearl is now being consumed?

**Comment by MK1Ultra** [comment]
it is still consumed,, but now you are aware of the problem. so i thought i can close the issue

**Comment by WanionCane** [comment]
ooh, you are saying that the Extremely Primordial Pearl shouldn't be consumed?

**Comment by MK1Ultra** [comment]
Yes. In regular Dire Table it is not consumed. Also the base item, the Primordial Pearl in thaumcraft, is not consumed during crafting

**Comment by WanionCane** [comment]
fixed, I am about to release a fix for it, thank you :)

**Comment by WanionCane** [comment]
I was thinking that the issue was that the Extremely Primordial Pearl was not being consumed, but the issue was the fact of it was being consumed lol
so, here's the [file](https://minecraft.curseforge.com/projects/avaritiaddons/files/2378543) =P

**Comment by MK1Ultra** [comment]
no, problem. i already tested it, its working now.
thank you :)
